train:
  seq_length: 2048
  epochs: 10000
  # epochs: 4
  total_steps: 6000
  batch_size: 8

  checkpoint_interval: 32000
  eval_interval: 500

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"
  save_best: False

model:
  model_path: "robertmyers/bpt-sft"
  num_layers_unfrozen: 16

tokenizer:
  tokenizer_path: "EleutherAI/gpt-j-6B"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 8.0e-6
    betas: [0.9, 0.97]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000
    eta_min: 8.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 64
  chunk_size: 16
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: "running"
  ref_mean: null
  ref_std: null
  cliprange_reward: 20
  gen_kwargs:
    max_new_tokens: 144
    top_k: 4
    top_p: 0.95
    do_sample: True
    temperature: 0.5
    penalty_alpha: 0.6
    repetition_penalty: 1.03
